### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-weather#2]
* [ ] Tests with jsdom ([example](https://github.com/sapegin/kurush/tree/master/web/tests)).
* [x] Travis CI.
* [ ] Include [Babel runtime](https://babeljs.io/docs/usage/runtime/) instead of polyfills in every module (?).
* [ ] [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) (?).
* [x] Show errors in the OS X Notification Center.
* [x] Exit on errors in non-watch mode.
* [ ] [React Hot Loader](https://github.com/gaearon/react-hot-loader).
